name: smart_trip_planner_flutter
version: 1.0.0+1
description: A Smart Trip Planner app using Flutter and Gemini Pro
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.0
  riverpod: ^2.6.1
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - .env